name: Build Release Android App

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Initialize NPM
        run: npm init -y

      - name: Install Cordova
        run: npm install -g cordova

      - name: Add Android Platform
        run: cordova platform add android

      # Recreates your Keystore file secretly
      - name: Decode Keystore
        run: echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > my-release-key.keystore

      # Builds and signs the APK (For your device)
      - name: Build and Sign Release APK
        run: |
          cordova build android --release \
          --keystore=my-release-key.keystore \
          --alias=${{ secrets.KEY_ALIAS }} \
          --storePassword=${{ secrets.KEY_PASSWORD }} \
          --password=${{ secrets.KEY_PASSWORD }}

      # Builds and signs the AAB (For Google Play Store)
      - name: Build and Sign Release AAB
        run: |
          cordova build android --release -- --packageType=bundle \
          --keystore=my-release-key.keystore \
          --alias=${{ secrets.KEY_ALIAS }} \
          --storePassword=${{ secrets.KEY_PASSWORD }} \
          --password=${{ secrets.KEY_PASSWORD }}

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: game-mcq-release-apk
          path: platforms/android/app/build/outputs/apk/release/*.apk

      - name: Upload Release AAB
        uses: actions/upload-artifact@v4
        with:
          name: game-mcq-release-aab
          path: platforms/android/app/build/outputs/bundle/release/*.aab
